// <auto-generated />
using System;
using BarbeariaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarbeariaAPI.Migrations
{
    [DbContext(typeof(BarbeariaContext))]
    [Migration("20260830215121_AtualizarPrecosServicos")]
    partial class AtualizarPrecosServicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarbeariaAPI.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BarbeiroId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BarbeiroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicoId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("BarbeariaAPI.Models.Barbeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Barbeiros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Vinicius Silva Lima"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Miguel Miyaki da Cruz"
                        });
                });

            modelBuilder.Entity("BarbeariaAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BarbeariaAPI.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Servicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Corte de cabelo completo",
                            DuracaoMinutos = 30,
                            Nome = "Cabelo completo",
                            Preco = 70.00m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Serviço completo de barba",
                            DuracaoMinutos = 30,
                            Nome = "Barba completa",
                            Preco = 70.00m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Design de sobrancelha",
                            DuracaoMinutos = 15,
                            Nome = "Sobrancelha",
                            Preco = 20.00m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Corte feito com máquina",
                            DuracaoMinutos = 20,
                            Nome = "Máquina",
                            Preco = 50.00m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Corte completo com hidratação",
                            DuracaoMinutos = 50,
                            Nome = "Cabelo completo + Hidratação",
                            Preco = 120.00m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Combo de cabelo, barba e sobrancelha",
                            DuracaoMinutos = 80,
                            Nome = "Cabelo completo + Barba + Sobrancelha",
                            Preco = 160.00m
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Depilação nasal com cera",
                            DuracaoMinutos = 20,
                            Nome = "Depilação a cera do nariz",
                            Preco = 35.00m
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Depilação da sobrancelha com cera",
                            DuracaoMinutos = 20,
                            Nome = "Depilação a cera da sobrancelha",
                            Preco = 35.00m
                        });
                });

            modelBuilder.Entity("BarbeariaAPI.Models.Agendamento", b =>
                {
                    b.HasOne("BarbeariaAPI.Models.Barbeiro", "Barbeiro")
                        .WithMany()
                        .HasForeignKey("BarbeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarbeariaAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarbeariaAPI.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barbeiro");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });
#pragma warning restore 612, 618
        }
    }
}
